[project]
authors = ["carschandler <92899389+carschandler@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ipdb_module_test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
ipython = ">=8.28.0,<9"
